### ISSUE TITLE
Go

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#107]
https://go-tour-jp.appspot.com
http://go.shibu.jp/effective_go.html

**Comment by hysryt** [comment]
# Docker でやる場合
**docker-compose.yml**
```yml
version: '3'
services:
  go:
    image: 'golang:latest'
    tty: true
    volumes:
      - './src:/go/src'
```
**コンテナ起動**
```
$ docker-compose up -d
$ docker-compose exec go /bin/bash
```
**フォルダ構成**
```
go/
 `- src/
     `- hello/
         `- hello.go
```
**hello.go**
```go
package main

import "fmt"

func main() {
	fmt.Printf("hello, world\n")
}
```
**コンパイル**
```
$ cd /go/src/hello
$ go build
$ ./hello
```
**コンテナ停止**
```
$ docker-compose down
```

作成したバイナリファイルはコンテナ内でのみ実行できる。
