### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#134]
https://travis-ci.org/

**Comment by hysryt** [comment]
# 概要
GitHubと連携したCI（継続的インテグレーション）サービス。
オープンソースプロジェクトであれば無料で利用できる。

GitHubにプッシュすると自動でテストが始まる。
`composer install` などが必要な場合は設定ファイルで実行するコマンドを指定する。

https://github.com/hysryt/searchrank

**Comment by hysryt** [comment]
# 複数のジョブの指定
1つの`.travis.yml`で複数のジョブを設定できる。
ジョブは最大200ジョブまで。

## マトリクス
言語や環境を複数設定することで、可能な全てのパターンのジョブが自動的に作成される。
次のような場合、2 \* 2 \* 2で8パターンのジョブに展開される。
```yaml
rvm:
  - 2.5
  - 2.2
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-3.0.x
env:
  - ISOLATED=true
  - ISOLATED=false
```

展開されるキーは言語によって異なる。

## jobs.include
マトリクスのようなあらゆるパターンが必要ではない場合は `jobs.include` で個別にジョブを指定する。
```yaml
jobs:
  include:
  - rvm: 2.5
    gemfile: gemfiles/Gemfile.rails-3.2.x
    env: ISOLATED=false
  - rvm: 2.2
    gemfile: gemfiles/Gemfile.rails-3.0.x
    env: ISOLATED=true
```

## jobs.exclude
マトリクスから特定のジョブを除外したい場合は `jobs.include` を指定する。
次のように指定することで、2 \* 2 \* 2 - 2 で 6パターンのジョブとなる。
```yaml
rvm:
  - 2.5
  - 2.2
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-3.0.x
env:
  - ISOLATED=true
  - ISOLATED=false
jobs:
  exclude:
  - rvm: 2.5
    gemfile: gemfiles/Gemfile.rails-3.2.x
    env: ISOLATED=true
  - rvm: 2.2
    gemfile: gemfiles/Gemfile.rails-3.2.x
    env: ISOLATED=true
```
