### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#15]
CSSのメタ言語
http://sass-lang.com/

**Comment by hysryt** [comment]
# Install
```
$ gem install sass
```
`gem`から`sass`をインストールする
```
$ sass -v
Sass 3.5.3 (Bleeding Edge)
```
`sass`がインストールされていることを確認

**Comment by hysryt** [comment]
# Preprocessing
以下のコマンドでコンパイルを行う
```
$ sass input.scss output.css
```
`input.scss`がコンパイルされ、`output.css`に出力される

---
## 例
#### SCSSファイル作成
```
$ vi input.scss
```
```scss
$primary-color: #333;

body {
  color: $primary-color;
}
```
#### sassコマンド実行
```
$ sass input.scss output.css
```
#### cssファイル確認
```
$ cat output.css
```
```css
body {
  color: #333; }

/*# sourceMappingURL=output.css.map */
```
`css`ファイルが生成されていることがわかる

**Comment by hysryt** [comment]
# Variables
`$`で変数を使用できる
### input.scss
```scss
$normal-size: 13px;
$primary-color: #333;

body {
  font-size: $normal-size;
  color: $primary-color;
}
```
### output.css
```css
body {
  font-size: 13px;
  color: #333; }

/*# sourceMappingURL=output.css.map */
```

**Comment by hysryt** [comment]
# Nesting
HTMLの階層をネストで記述できる
### input.scss
```scss
section {
  h1 {
    font-size: 20px;
  }

  p {
    font-size: 13px;
  }
}
```
### output.css
```css
section h1 {
  font-size: 20px;
}
section p {
  font-size: 13px;
}

/*# sourceMappingURL=output.css.map */
```

**Comment by hysryt** [comment]
# Partials / Import
一部を別ファイルにすることができる
別ファイルはファイル名の先頭に`_`をつける
別ファイルは`@import`で読み込む 
`@import`で指定する名前には`_`及び拡張子は必要ない
### _reset.scss
```scss
html, body, div, p {
  margin: 0;
  padding: 0;
}
```
### input.scss
```scss
@import 'reset';

body {
  font-size: 10px;
}
```
### output.css
```css
html, body, div, p {
  margin: 0;
  padding: 0;
}

body {
  font-size: 10px;
}
```

**Comment by hysryt** [comment]
# Mixins
共通部分を`@mixin`で一箇所にまとめることができる
ベンダープレフィックスをまとめるのに使われたりする
`@mixin`で指定したスタイルは`@include`で使用できる
### input.scss
```scss
@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
  -moz-border-radius: $radius;
  -ms-border-radius: $radius;
  border-radius: $radius;
}

.box1 {
  @include border-radius(10px);
}

.box2 {
  @include border-radius(20px);
}
```
### output.css
```css
.box1 {
  -webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  -ms-border-radius: 10px;
  border-radius: 10px;
}

.box2 {
  -webkit-border-radius: 20px;
  -moz-border-radius: 20px;
  -ms-border-radius: 20px;
  border-radius: 20px;
}

/*# sourceMappingURL=output.css.map */
```

**Comment by hysryt** [comment]
# Extend
`@extend`でスタイルを継承できる
おそらくもっとも扱いが難しいディレクティブ
### input.scss
```scss
.message {
  width: 100%;
  border: solid 1px black;
}

.message .small {
  width: 50%;
}

.success {
  @extend .message;
  border-color: green;
}
```
`.success`は`.message`を継承するため、`.message`が使えるところには`.success`も使えるようになる
具体的には`.success .small`という使い方ができるように変換される
### output.css
```css
.message, .success {
  width: 100%;
  border: solid 1px black;
}

.message .small, .success .small {
  width: 50%;
}

.success {
  border-color: green;
}

/*# sourceMappingURL=output.css.map */
```
`.message`が`.message, .success`に変換されているだけでなく、`.message .small`が`.message .small, .success .small `に変換されていることに注目

`.message`のスタイルだけでなく、ユースケース自体を継承していると言える
`.message`が使えるところは`.success`に代替可能ということ

**Comment by hysryt** [comment]
# Operators
四則演算が可能
### input.scss
```scss
.box1 {
  width: (100% / 3);
}

.box2 {
  width: (980px / 2);
}
```
### output.css
```css
.box1 {
  width: 33.3333333333%;
}

.box2 {
  width: 490px;
}

/*# sourceMappingURL=output.css.map */
```

**Comment by hysryt** [comment]
# !default
変数に`!default`フラグを使用すると、**すでに定義されている場合は上書きしない**
### input.scss
```scss
$test: 13px;
$test: 15px;
$test: 18px !default;

body {
  font-size: $test;
}
```
### output.css
```css
body {
  font-size: 15px;
}

/*# sourceMappingURL=output.css.map */
```
`$test`には1行目で`13px`が代入される
2行目で`15px`が再代入される
3行目では`!default`がついているため代入**されない**
結果`$test`には`15px`が代入されている

**Comment by hysryt** [comment]
# css.map
ソースマップ
あるスタイルがどのファイルに記述されているかが記されているファイル
デバッグ時に役立つが無くても良い

**Comment by hysryt** [comment]
# %
Sass内でのクラス定義をする
```scss
%common {
  padding: 0;
  margin: 0;
}

.list {
  @extend %common;
}

.box {
  @extend %common;
}
```
`column`自体はCSSファイルに出力されないが、`.list`、`.box`には`common`の内容が継承される

**Comment by hysryt** [comment]
# @for
```scss
@for $i from 1 through 5 {
  .line-height-#{$i} {
    line-height: $i;
  }
}
```

**Comment by hysryt** [comment]
# ディレクトリ単位でコンパイル
`node-sass` を使っている場合は以下のコマンドでディレクトリ内の全てのscssをコンパイルできる。
```
$ node-sass src/scss -o ../css
```
`src/scss` ディレクトリに `style.scss` と `common.scss` がある場合、それぞれコンパイルされて `../css` ディレクトリに `style.css` と `common.css` が作成される。
```
$ node-sass src/scss -o ../css --watch
```
`--watch` を指定した場合、**変更があったファイルのみ**リアルタイムでコンパイルされる。
モジュール（`_***.scss`）を変更した場合、**そのモジュールに依存するファイルのみ**コンパイルされる。

**Comment by hysryt** [comment]
# Dart Sass
[LibSassは廃止された](https://sass-lang.com/blog/libsass-is-deprecated)ので今後はDart Sassを使用する。
npmパッケージは `node-sass` から `sass` に変更。

## Install
```
npm install -D sass
```

## Command
#### input.scssをoutput.cssにトランスパイルする
```
sass input.scss:output.css
```

#### inputdirディレクトリの中のscssをトランスパイルし、outputdirディレクトリに設置する
```
sass inputdir:outputdir
```

## Option
#### `--watch`
ウォッチモード

#### `--embed-source-map`
ソースマップをcssファイル内に含める

**Comment by hysryt** [comment]
# @use
https://sass-lang.com/documentation/at-rules/use

scssファイル間の依存関係を指定する際に使用する。
`@use` はファイルの先頭に記述する必要がある。

`@import` は単純なファイルの結合だったのに対し、`@use` はモジュールとしてロードという意味合いが強くなっている。

`@use` でロードしたモジュールが持つ変数やmixin、関数を使用する場合は名前空間の指定が必要となる。

#### _variable.scss
```scss
$color: red;
```

#### style.scss
```scss
@use 'variable';

.test {
  color: variable.$color;
}
```

`as` で名前空間名を変更できる。

#### style.scss
```scss
@use 'variable' as v;

.test {
  color: v.$color;
}
```

`as *` とすれば名前空間なしでの読み込みが可能。


#### style.scss
```scss
@use 'variable' as *;

.test {
  color: $color;
}
```

----

`@use` で同じモジュールが複数のモジュールから参照されている場合でも、重複して読み込まれることはない。
トランスパイル時に依存関係が解決され、適切な順序で一度だけ読み込まれる。

例えば以下の場合

#### style.scss
```scss
@use 'pc';
@use 'sp';
```

#### _pc.scss
```scss
@use 'base';
```

#### _sp.scss
```scss
@use 'base';
```

#### _base.scss
```scss
$color: red;
.base {
  color: $color;
}
```

- `style.scss` は `_pc.scss` と `_sp.scss` に依存する
- `_pc.scss` は `_base.scss` に依存する
- `_sp.scss` は `_base.scss` に依存する

この場合 `_base.scss` は2つのファイルから依存されているが、2度読み込まれることはない。
最終的にトランスパイルされるcssファイルは

```css
.base {
  color: red;
}
```

となる。

また、`@import` とは異なり、この場合に `style.scss` は `$color` は使用できない。
モジュールを跨いで変数やmixinなどを使用する場合は `@forward` を使用する必要がある。

**Comment by hysryt** [comment]
# @forward
モジュールをロードする。
@useとは異なり、@forwardでロードしたモジュールの変数や関数、mixinはさらに公開され、@useでロードすれば使用できる。
利便性や可読性のために、変数やmixinなどのモジュールをまとめて一つのモジュールととして扱いたい場合に使用することが多い。

#### _variable.scss
```scss
$color: red;
```

#### _mixin.scss
```scss
@mixin hidden {
  opacity: 0;
  visibility: hidden;
}
```

#### _bootstrap.scss
```scss
@forward 'variable';
@forward 'mixin';
```

#### style.scss
```scss
@use 'bootstrap';

.test {
  color: bootstrap.$color;
  @include bootstrap.hidden;
}
```

この場合は `as *` でロードした方が使いやすいかもしれない。

```scss
@use 'bootstrap' as *;

.test {
  color: $color;
  @include hidden;
}
```
