### ISSUE TITLE
Varnish

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#188]

**Comment by hysryt** [comment]
**docker-compose.yml**
```yml
version: "3"

services:
  app:
    image: php:8-apache
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
  
  cache:
    image: varnish:7.0
    ports:
      - 8081:80
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
    tmpfs:
      - /var/lib/varnish:exec
```

**default.vcl**
```vcl
vcl 4.0;

backend default {
  .host = "app:80";
}
```
