### ISSUE TITLE
CSS Flexbox

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#20]
https://liginc.co.jp/web/html-css/css/21024

**Comment by hysryt** [comment]
# Flexbox
- Flexboxコンテナー要素
- Flexboxアイテム要素

Flexboxコンテナー要素の子要素は全てFlexboxアイテム要素となる

**Comment by hysryt** [comment]
# Flexboxコンテナー
`display: flex`を指定する

**Comment by hysryt** [comment]
# Flexboxアイテム
Flexboxコンテナーの子要素

## `flex-grow`プロパティ
## `flex-shrink`プロパティ
## `flex-basis`プロパティ
## `flex`プロパティ
`flex-grow`、`flex-shrink`、`flex-basis`をまとめて指定するプロパティ
```
flex: <flex-growの値> <flex-shrinkの値> <flex-basisの値>
```

**Comment by hysryt** [comment]
# Example
### 三等分
#### CSS
```css
.flex-container {
  display: flex;
  flex-wrap: wrap;
}

.item {
  flex-basis: 33.3333%;  /* 二等分の場合は50%,、四等分の場合は25% */
}
```
#### HTML
```html
<div class="flex-container">
  <div class="item">1</div>
  <div class="item">2</div>
  <div class="item">3</div>
  <div class="item">4</div>
  <div class="item">5</div>
  <div class="item">6</div>
  <div class="item">7</div>
</div>
