### ISSUE TITLE
Wordmove

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#38]
ローカルのWordPressをリモートにデプロイする
https://github.com/welaika/wordmove

**Comment by hysryt** [comment]
# Install
```
$ gem install wordmove
```
Ruby2.5では動かないので2.4.3を使用する（2017.12.27時点）

**Comment by hysryt** [comment]
# movefile.yml
各種設定は`movefile.yml`に記述する
`wordmove init`で雛形を作成できる
```
$ wordmove init
```

**Comment by hysryt** [comment]
# デプロイ
```
$ wordmove push --all
```
`--all`オプションでDB、WordPress全てのファイルをデプロイできる。
二度目以降は差分がデプロイされる模様。

**Comment by hysryt** [comment]
# home と siteurl が違う場合
movefile.yml の `vhost` に siteurl を設定する。
wp-config.php で home を設定する。

**例：`wp`ディレクトリに WordPress を設置する場合**

```yml
# home ： http://localhost
# site_url ： http://localhost/wp

local:
  vhost: http://localhost/wp
  wordpress_path: /var/www/html/wp
```

**Comment by hysryt** [comment]
# forbid
Wordmove 3.0 以降では production セクションに forbid セクションを追加できるようになった。
forbid セクションを設定することで pull や push アクションを禁止させることができる。

```yml
production:
  forbid:
    push:
      db: false
      plugins: false
      themes: false
      languages: false
      uploads: false
      mu-plugins: false
    pull:
      db: false
      plugins: false
      themes: false
      languages: false
      uploads: false
      mu-plugins: false
```

`true` で禁止、`false` で許可する。（つまり上の例では全て許可となる）
デフォルト値が `false` なため、`true` にしたい項目だけ記述すれば良い。

`true` に設定した項目を pull または push しようとすると以下のように Warning が発生し、実行されない。

```
▬▬ Pushing Db ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ⚠️  warning | You tried to push db, but is forbidden by configuration. Skipping
```
