### ISSUE TITLE
VCCW

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#42]
あらかじめVagrantfileなどが入ったzipを公式サイトからダウンロード、展開、フォルダ移動しておく
```
$ vagrant plugin install vagrant-hostsupdater
$ vagrant box add vccw-team/xenial64
$ vagrant up
```

**Comment by hysryt** [comment]
# ブリッジ接続での仮想マシンの作成
## site.yml
```yml
hostname: 192.168.0.200
# ip: 192.168.33.10
```
- `hostname` をIPアドレスに変更
- `ip` をコメントアウト

## Vagrantfile
```yml
#  config.vm.network :private_network, ip: _conf['ip']
  config.vm.network :public_network, ip: "192.168.0.200"
```
- `private_network`の行をコメントアウト
- その下に `public_network`の行を追加。IPアドレスには適切なものを指定。

**Comment by hysryt** [comment]
# プロビジョンの追加
Vagrantfile と同じディレクトリに `provision-post.sh` を置くことで VCCW のプロビジョンの後に処理を追加できる。
```sh
#!/usr/bin/env bash

# wordmove の除外ファイルに node_modules を追加
cd /vagrant
sed -i -e '/^  exclude:$/a\    - "node_modules"' Movefile.yml
```

**Comment by hysryt** [comment]
# Xdebug
デフォルトで組み込み済み。
デフォルトの php.ini は以下の通り。
```yml
php_ini:
  date.timezone: UTC
  default_charset: UTF-8
  mbstring.language: neutral
  mbstring.internal_encoding: UTF-8
  post_max_size: 1024M # Same with VVV
  short_open_tag: Off
  session.save_path: /tmp
  upload_max_filesize: 1024M # Same with VVV
  xdebug.remote_enable: true
  xdebug.remote_host: 127.0.0.1
  xdebug.remote_port: 9000
  xdebug.profiler_enable: true
  xdebug.idekey: VCCWDEBUG
  xdebug.remote_connect_back: true
  xdebug.remote_autostart: true
```

`xdebug.remote_connect_back` が `true` になっているので特に設定の変更は必要ない。

**Comment by hysryt** [comment]
# wordpress をインストールしない
```yml
---
- hosts: all
  vars:
    path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}"
    user: "{{ ansible_env.USER | default( 'ubuntu' ) }}"

  tasks:

  # Database Settings
  - name: Create Database
    mysql_db:
      login_user: root
      name: "{{ vccw.db_name }}"
      state: present

  - name: Create MySQL user
    mysql_user:
      login_user: root
      name: "{{ vccw.db_user }}"
      password: "{{ vccw.db_pass }}"
      priv: "{{ vccw.db_name }}.*:ALL"
      host: "%"
      state: present

  - name: "Change owner of the {{ path }}"
    become: yes
    file:
      path: "{{ path }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      recurse: yes

  - name: "Remove index.html from document root"
    become: yes
    file:
      path: "{{ path }}/index.html"
      state: absent
```

**Comment by hysryt** [comment]
# リモートから WordPress 環境を取得する際の手順
## site.yml の編集
- リモートの `wp-config.php` からデータベース情報を取得。
  - ホスト名
  - ユーザ名
  - パスワード
  - データベース名

- リモートの `wp-config.php` からテーブルのプレフィックスを取得。
  `wp_` 以外の場合は `site.yml` を変更。
  ```yml
  db_prefix: wp_
  ```
- リモートの `wp-config.php` および データベースから home と siteurl を取得。
  home と siteurl が異なる場合、`site.yml` を変更
  ```yml
  # home が http://example.com
  # siteurl が http://example.com/wp の場合
  wp_siteurl: 'wp'
  ```
- `vagrant up`

## Movefile.yml の編集
- リモートの home と siteurl を確認。
  home と siteurl が異なる場合、 `Movefile.yml` の `vhost` と `wordpress_path` を siteurl のパスに合わせる。

  ```yml
  # home が http://example.com
  # siteurl が http://example.com/wp の場合
  vhost: http://example.com/wp
  wordpress_path: /public_html/wp
  ```
  `local` と `production` の両方を変更する。（ `site.yml` を正しく設定していれば `local` は自動的に設定される）

- `production` のデータベース情報を編集。
  `port:` の行はほとんど使用しないので消す。

- FTP 情報を追加。
  `ssh:` のセクションを消して `ftp:` を追加する。
