### ISSUE TITLE
CSS フォント

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#67]

**Comment by hysryt** [comment]
# 文字サイズ
単位は `px`、`%`、`rem`、`em`、`vw` など

`px` はブラウザや端末での文字サイズ設定を**無視する**。
`rem` や `em` も、 `px` に依存する場合は同じように**無視されることになる**。
ユーザーの文字サイズ設定を尊重する場合は `px` は使用せずに、ルートで `%` 指定、その他では `rem` 指定するのが良い。

ルートで `rem` や `em` を指定した場合はブラウザや端末の文字サイズ設定を元に計算する。
例えばルードで `font-size: 1rem` とした場合は `font-size: 100%` とした場合と同等となる。

## デフォルト値
多くのブラウザや端末で、文字サイズのデフォルト値は `16px` になっている模様。

## 設定例1
```css
html {
  /* スマホの場合、ルートの文字サイズを 14px にする。
     ユーザ設定を尊重するため px ではなく % で指定。 */
  font-size: 87.5%;

  /* タブレット以上の場合、ルートの文字サイズを 16px にする。
     ユーザ設定を尊重するため px ではなく % で指定。 */
  @media (min-width: 768px) {
    font-size: 100%;
  }
}
```
スマホでも文字サイズのデフォルトは `16px` になっていることが多いが、少し大きいため `14px` にする。
この設定によって、スマホの場合は `1rem = 14px`、タブレットやPCの場合は `1rem = 16px` となる。

## 設定例2
```css
html {
  /* 文字サイズを 10px にする。
     ユーザ設定を尊重するため px ではなく % で指定。 */
  font-size: 62.5%;
}

body {
  /* スマホでは 14px */
  font-size: 1.4rem;

  /* タブレット以上では 16px */
  @media (min-width: 768px) {
    font-size: 1.6rem;
  }
}
```
設定例1と同じようにスマホでは 14px、タブレット・PCでは 16px にするが、`rem` の基準を 10px（62.5%） にする。
これによって `1.6rem = 16px` のように、`px` から `rem` への変換が簡単になる。
`1px = 1rem` となるが、ユーザの文字サイズ設定を尊重するため、`px` を使うよりもユーザビリティが高い。

ただし「ちょっと大きい文字サイズを指定したい」といった場合、設定例1では `1.5rem` とすればスマホでは `21px`、タブレット・PCでは `24px` とできるのに対し、設定例2では個別に `2.1rem` と `2.4rem` を指定しなければならない。

スマホとタブレット・PCで、同じ割合で文字を拡大縮小したいというケースが少ない気もするので設定例2でいいかもしれない。そもそもPCで `16px` というのも結構大きい気がするので全ての端末で `14px` とかに揃えるのもあり。 

## 設定例3
```css
html {
  font-size: 62.5%;
}

body {
  font-size: 1.4rem;
}
```
スマホ・タブレット・PCの全てで `14px` に設定。
- サイズが丁度いい。
- `1rem = 1px` だからわかりやすい。
- `px` を使わないのでユーザの文字サイズ設定も尊重する。

案件によってスマホとPCで基準サイズが違う（スマホは14px、PCは16pxとか）場合もあるので、その場合は設定例2のように `body` 内でメディアクエリを使って分ける。
