### ISSUE TITLE
CSS メディアクエリ

### ISSUE THREAD

**Issue by hysryt** [hysryt/wiki#75]

**Comment by hysryt** [comment]
# デバイスピクセル比
デバイスピクセル比での切り替えには `min(max)-resolution` を使用する。
Safari は対応していないので代わりに `-webkit-min(max)-device-pixcel-ratio` を使用する。

```css
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx) {
  body {
    background-image: url('bg@2x.jpg');
  }
}
```

`dppx` は `dot per pixel` の略で 1px あたりのドット数。距離で見た場合の 1px なので デバイスピクセル比が 2 の場合は 2dppx。4dppxではない。

`min(max)-resolution` には `dppx` 以外に `dpi` 、`dpcm` が使用できるが、デバイスピクセル比を指定するなら `min(max)-device-pixel-ratio` の指定値に単位をつけるだけの `dppx` が一番使いやすい。

`dpi` でも記述はできる。CSSの仕様では `1インチ` は `96px` 。Retina ディスプレイだろうが普通のディスプレイだろうが CSS 上では `1インチ = 96px`なので、 `1dppx` の時は `96dpi` となる。これをもとに計算すると `2dppx` の場合は `192dpi` になる。

```css
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  body {
    background-image: url('bg@2x.jpg');
  }
}
```

IE11 は`dppx` に対応していないので `dpi` で記述する。しかし IE11 かつ デバイスピクセル比が 1 より大きい環境はかなり少ないし `1dppx = 96dpi` というのも覚えづらいので無視してもいいと思う。

`min(max)-device-pixel-ratio` は Apple が Retina ディスプレイ開発時に作った独自メディアクエリで、標準規格ではない。

https://developer.mozilla.org/ja/docs/Web/CSS/resolution
